scss_files: 'juju-gui/**/*.scss'

exclude: 'juju-gui/static/gui/src/app/assets/css/plugins/**'

linters:
  SelectorFormat:
    convention: hyphenated_BEM

  IdSelector:
    severity: warning

  VendorPrefix:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  PropertySortOrder:
    enabled: false
