domain: jujucharms.com

image: prod-comms.docker-registry.canonical.com/jujucharms.com

useProxy: false

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'jujucharms.com' ) {
      rewrite ^ https://jujucharms.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
